# Here I don't need anything of ML
FROM python:3.12.13-bookworm

# Pulling uv instead of pip as package manager
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# cd like
WORKDIR /app

# Optimizations (from uv Astral docs): 
ENV UV_COMPILE_BYTECODE=1 
ENV UV_LINK_MODE=copy

# Dendence info (readme is to comply with the .toml)
COPY pyproject.toml uv.lock README.md ./

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project

# Application files
COPY    src/enterprise_rag/__init__.py \
        src/enterprise_rag/connection_config.py \ 
        src/enterprise_rag/ui.py \
        /app/src/enterprise_rag/

# Instaling dependence
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen 

# Expose port for gradio (the same specified in the docker compose)
EXPOSE 7860 

# cd like: this allows to use local imports
WORKDIR /app/src/enterprise_rag

# Run the UI 
CMD ["uv", "run", "python", "ui.py"]